# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_processing_system7/xlnx_processing_system7.srcs/sources_1/ip/xlnx_processing_system7/xlnx_processing_system7.xci
# IP: The module: 'xlnx_processing_system7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_processing_system7/xlnx_processing_system7.srcs/sources_1/ip/xlnx_processing_system7/xlnx_processing_system7.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_processing_system7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_processing_system7/xlnx_processing_system7.srcs/sources_1/ip/xlnx_processing_system7/xlnx_processing_system7.xci
# IP: The module: 'xlnx_processing_system7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_processing_system7/xlnx_processing_system7.srcs/sources_1/ip/xlnx_processing_system7/xlnx_processing_system7.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_processing_system7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
