# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-10151-boyer-Inspiron-16-Plus/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/boyer/git_complet_pro/Thales_contest/fpga/src/axi_sd_bridge/include
    /home/boyer/git_complet_pro/Thales_contest/src/common_cells/include
    /home/boyer/git_complet_pro/Thales_contest/fpga/src
    /home/boyer/git_complet_pro/Thales_contest/src/common_cells/include/common_cells
    /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_clk_gen/ip
    /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/ip/hdl
    /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/ip/hdl
  } -define BRAM=BRAM {
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/zybo-z7-20.svh
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/include/common_cells/registers.svh
      /home/boyer/git_complet_pro/Thales_contest/include/riscv_pkg.sv
      /home/boyer/git_complet_pro/Thales_contest/src/riscv-dbg/src/dm_pkg.sv
      /home/boyer/git_complet_pro/Thales_contest/include/ariane_pkg.sv
      /home/boyer/git_complet_pro/Thales_contest/src/CFI.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpga-support/rtl/SyncSpRamBeNx64.sv
      /home/boyer/git_complet_pro/Thales_contest/src/alu.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/amo_alu.sv
      /home/boyer/git_complet_pro/Thales_contest/src/amo_buffer.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_timer/apb_timer.sv
      /home/boyer/git_complet_pro/Thales_contest/src/register_interface/src/apb_to_reg.sv
      /home/boyer/git_complet_pro/Thales_contest/tb/ariane_soc_pkg.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi/src/axi_pkg.sv
      /home/boyer/git_complet_pro/Thales_contest/include/ariane_axi_pkg.sv
      /home/boyer/git_complet_pro/Thales_contest/src/ariane.sv
      /home/boyer/git_complet_pro/Thales_contest/src/register_interface/src/reg_intf_pkg.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane_peripherals_xilinx.sv
      /home/boyer/git_complet_pro/Thales_contest/src/ariane_regfile_ff.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/axi2apb/src/axi2apb_64_32.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_mem_if/src/axi2mem.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_AR_allocator.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_AW_allocator.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_BR_allocator.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_BW_allocator.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_DW_allocator.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_adapter.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_adapter_32.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_address_decoder_AR.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_address_decoder_AW.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_address_decoder_BR.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_address_decoder_BW.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_address_decoder_DW.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/axi_slice/src/axi_ar_buffer.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/axi_slice/src/axi_aw_buffer.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/axi_slice/src/axi_b_buffer.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi/src/axi_cut.sv
      /home/boyer/git_complet_pro/Thales_contest/include/axi_intf.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi/src/axi_join.sv
      /home/boyer/git_complet_pro/Thales_contest/src/clint/axi_lite_interface.sv
      /home/boyer/git_complet_pro/Thales_contest/src/util/axi_master_connect.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi/src/axi_multicut.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_multiplexer.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_node.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_node_arbiter.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_node_intf_wrap.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_node_wrap_with_slices.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/axi_slice/src/axi_r_buffer.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_request_block.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_riscv_atomics/src/axi_res_tbl.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_node/src/axi_response_block.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_riscv_atomics/src/axi_riscv_amos.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_riscv_atomics/src/axi_riscv_amos_alu.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_riscv_atomics/src/axi_riscv_atomics.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_riscv_atomics/src/axi_riscv_lrsc.sv
      /home/boyer/git_complet_pro/Thales_contest/src/axi_shim.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/axi_slice/src/axi_single_slice.sv
      /home/boyer/git_complet_pro/Thales_contest/src/util/axi_slave_connect.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/axi_slice/src/axi_w_buffer.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/axis_gmii_rx.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/axis_gmii_tx.sv
      /home/boyer/git_complet_pro/Thales_contest/src/frontend/bht.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/bootrom/bootrom.sv
      /home/boyer/git_complet_pro/Thales_contest/src/branch_unit.sv
      /home/boyer/git_complet_pro/Thales_contest/src/frontend/btb.sv
      /home/boyer/git_complet_pro/Thales_contest/include/std_cache_pkg.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/cache_ctrl.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/cdc_2phase.sv
      /home/boyer/git_complet_pro/Thales_contest/src/clint/clint.sv
      /home/boyer/git_complet_pro/Thales_contest/src/tech_cells_generic/src/cluster_clock_inverter.sv
      /home/boyer/git_complet_pro/Thales_contest/src/commit_stage.sv
      /home/boyer/git_complet_pro/Thales_contest/src/compressed_decoder.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
      /home/boyer/git_complet_pro/Thales_contest/src/controller.sv
      /home/boyer/git_complet_pro/Thales_contest/src/csr_buffer.sv
      /home/boyer/git_complet_pro/Thales_contest/src/csr_regfile.sv
      /home/boyer/git_complet_pro/Thales_contest/src/riscv-dbg/debug_rom/debug_rom.sv
      /home/boyer/git_complet_pro/Thales_contest/src/decoder.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
      /home/boyer/git_complet_pro/Thales_contest/src/riscv-dbg/src/dm_csrs.sv
      /home/boyer/git_complet_pro/Thales_contest/src/riscv-dbg/src/dm_mem.sv
      /home/boyer/git_complet_pro/Thales_contest/src/riscv-dbg/src/dm_sba.sv
      /home/boyer/git_complet_pro/Thales_contest/src/riscv-dbg/src/dm_top.sv
      /home/boyer/git_complet_pro/Thales_contest/src/riscv-dbg/src/dmi_cdc.sv
      /home/boyer/git_complet_pro/Thales_contest/src/riscv-dbg/src/dmi_jtag.sv
      /home/boyer/git_complet_pro/Thales_contest/src/riscv-dbg/src/dmi_jtag_tap.sv
      /home/boyer/git_complet_pro/Thales_contest/src/dromajo_ram.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/dualmem_widen.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/dualmem_widen8.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/eth_mac_1g.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/eth_mac_1g_rgmii.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/eth_mac_1g_rgmii_fifo.sv
      /home/boyer/git_complet_pro/Thales_contest/src/ex_stage.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/exp_backoff.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/deprecated/fifo_v1.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/deprecated/fifo_v2.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/fifo_v3.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_pkg.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_cast_multi.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_classifier.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_divsqrt_multi.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_fma.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_fma_multi.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_noncomp.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_opgroup_block.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_opgroup_fmt_slice.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_opgroup_multifmt_slice.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_rounding.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpnew_top.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu_wrap.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/framing_top.sv
      /home/boyer/git_complet_pro/Thales_contest/src/frontend/frontend.sv
      /home/boyer/git_complet_pro/Thales_contest/src/id_stage.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/iddr.sv
      /home/boyer/git_complet_pro/Thales_contest/src/frontend/instr_queue.sv
      /home/boyer/git_complet_pro/Thales_contest/src/instr_realign.sv
      /home/boyer/git_complet_pro/Thales_contest/src/frontend/instr_scan.sv
      /home/boyer/git_complet_pro/Thales_contest/src/issue_read_operands.sv
      /home/boyer/git_complet_pro/Thales_contest/src/issue_stage.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/lfsr_8bit.sv
      /home/boyer/git_complet_pro/Thales_contest/src/load_store_unit.sv
      /home/boyer/git_complet_pro/Thales_contest/src/load_unit.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/lzc.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/miss_handler.sv
      /home/boyer/git_complet_pro/Thales_contest/src/mmu.sv
      /home/boyer/git_complet_pro/Thales_contest/tb/common/mock_uart.sv
      /home/boyer/git_complet_pro/Thales_contest/src/mult.sv
      /home/boyer/git_complet_pro/Thales_contest/src/multiplier.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/oddr.sv
      /home/boyer/git_complet_pro/Thales_contest/src/perf_counters.sv
      /home/boyer/git_complet_pro/Thales_contest/src/rv_plic/rtl/plic_regmap.sv
      /home/boyer/git_complet_pro/Thales_contest/src/rv_plic/rtl/plic_top.sv
      /home/boyer/git_complet_pro/Thales_contest/src/pmp/src/pmp.sv
      /home/boyer/git_complet_pro/Thales_contest/src/pmp/src/pmp_entry.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/popcount.sv
      /home/boyer/git_complet_pro/Thales_contest/src/fpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
      /home/boyer/git_complet_pro/Thales_contest/src/ptw.sv
      /home/boyer/git_complet_pro/Thales_contest/src/tech_cells_generic/src/pulp_clock_mux2.sv
      /home/boyer/git_complet_pro/Thales_contest/src/frontend/ras.sv
      /home/boyer/git_complet_pro/Thales_contest/src/re_name.sv
      /home/boyer/git_complet_pro/Thales_contest/src/register_interface/src/reg_intf.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/rgmii_core.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/rgmii_lfsr.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/rgmii_phy_if.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/rgmii_soc.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/rr_arb_tree.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/rstgen.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/rstgen_bypass.sv
      /home/boyer/git_complet_pro/Thales_contest/src/rv_plic/rtl/rv_plic_gateway.sv
      /home/boyer/git_complet_pro/Thales_contest/src/rv_plic/rtl/rv_plic_target.sv
      /home/boyer/git_complet_pro/Thales_contest/src/scoreboard.sv
      /home/boyer/git_complet_pro/Thales_contest/src/serdiv.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/shift_reg.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/spill_register.sv
      /home/boyer/git_complet_pro/Thales_contest/src/util/sram.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/ariane-ethernet/ssio_ddr_in.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/std_cache_subsystem.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/std_icache.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/std_nbdcache.sv
      /home/boyer/git_complet_pro/Thales_contest/src/store_buffer.sv
      /home/boyer/git_complet_pro/Thales_contest/src/store_unit.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/stream_arbiter.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/stream_arbiter_flushable.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/stream_demux.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/stream_mux.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/tag_cmp.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_timer/timer.sv
      /home/boyer/git_complet_pro/Thales_contest/src/tlb.sv
      /home/boyer/git_complet_pro/Thales_contest/src/common_cells/src/unread.sv
      /home/boyer/git_complet_pro/Thales_contest/include/wt_cache_pkg.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/wt_axi_adapter.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/wt_cache_subsystem.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/wt_dcache.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/wt_dcache_ctrl.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/wt_dcache_mem.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/wt_dcache_missunit.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/wt_dcache_wbuffer.sv
      /home/boyer/git_complet_pro/Thales_contest/src/cache_subsystem/wt_icache.sv
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/cva6_zybo_z7_20.sv
      /home/boyer/App/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/boyer/App/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/boyer/git_complet_pro/Thales_contest/fpga/src/axi_sd_bridge/include
    /home/boyer/git_complet_pro/Thales_contest/src/common_cells/include
    /home/boyer/git_complet_pro/Thales_contest/fpga/src
    /home/boyer/git_complet_pro/Thales_contest/src/common_cells/include/common_cells
    /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_clk_gen/ip
    /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/ip/hdl
    /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/ip/hdl
  } -define BRAM=BRAM {
      ./.Xil/Vivado-10151-boyer-Inspiron-16-Plus/realtime/xlnx_blk_mem_gen_stub.v
      ./.Xil/Vivado-10151-boyer-Inspiron-16-Plus/realtime/xlnx_clk_gen_stub.v
      ./.Xil/Vivado-10151-boyer-Inspiron-16-Plus/realtime/xlnx_axi_dwidth_converter_dm_master_stub.v
      ./.Xil/Vivado-10151-boyer-Inspiron-16-Plus/realtime/xlnx_axi_dwidth_converter_dm_slave_stub.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/apb_uart.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/slib_clock_div.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/slib_counter.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/slib_edge_detect.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/slib_fifo.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/slib_input_filter.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/slib_input_sync.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/slib_mv_filter.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/uart_baudgen.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/uart_interrupt.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/uart_receiver.vhd
      /home/boyer/git_complet_pro/Thales_contest/fpga/src/apb_uart/src/uart_transmitter.vhd
    }
      rt::read_vhdl -lib xpm /home/boyer/App/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top cva6_zybo_z7_20
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-10151-boyer-Inspiron-16-Plus/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
