# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_blk_mem_gen/xlnx_blk_mem_gen.srcs/sources_1/ip/xlnx_blk_mem_gen/xlnx_blk_mem_gen.xci
# IP: The module: 'xlnx_blk_mem_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_blk_mem_gen/xlnx_blk_mem_gen.srcs/sources_1/ip/xlnx_blk_mem_gen/xlnx_blk_mem_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_blk_mem_gen'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_blk_mem_gen/xlnx_blk_mem_gen.srcs/sources_1/ip/xlnx_blk_mem_gen/xlnx_blk_mem_gen.xci
# IP: The module: 'xlnx_blk_mem_gen' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/boyer/git_complet_pro/Thales_contest/fpga/xilinx/xlnx_blk_mem_gen/xlnx_blk_mem_gen.srcs/sources_1/ip/xlnx_blk_mem_gen/xlnx_blk_mem_gen_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlnx_blk_mem_gen'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
